apiVersion: v1
kind: Service
metadata:
  name: britamglapi-prod-service
  labels:
    app: britamglapi-prod
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30004
    protocol: TCP
  selector:
    app: britamglapi-prod