apiVersion: v1
kind: Service
metadata:
  name: britamglapi-staging-service
  labels:
    app: britamglapi-uat
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30006
    protocol: TCP
  selector:
    app: britamglapi-uat